// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/two.proto

package two

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Two service

func NewTwoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Two service

type TwoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Two_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Two_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Two_BidiStreamService, error)
}

type twoService struct {
	c    client.Client
	name string
}

func NewTwoService(name string, c client.Client) TwoService {
	return &twoService{
		c:    c,
		name: name,
	}
}

func (c *twoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Two.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twoService) ClientStream(ctx context.Context, opts ...client.CallOption) (Two_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Two.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &twoServiceClientStream{stream}, nil
}

type Two_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type twoServiceClientStream struct {
	stream client.Stream
}

func (x *twoServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *twoServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *twoServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twoServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twoServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twoServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *twoService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Two_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Two.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &twoServiceServerStream{stream}, nil
}

type Two_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type twoServiceServerStream struct {
	stream client.Stream
}

func (x *twoServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *twoServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *twoServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twoServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twoServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twoServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *twoService) BidiStream(ctx context.Context, opts ...client.CallOption) (Two_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Two.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &twoServiceBidiStream{stream}, nil
}

type Two_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type twoServiceBidiStream struct {
	stream client.Stream
}

func (x *twoServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *twoServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *twoServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twoServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twoServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twoServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *twoServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Two service

type TwoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Two_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Two_ServerStreamStream) error
	BidiStream(context.Context, Two_BidiStreamStream) error
}

func RegisterTwoHandler(s server.Server, hdlr TwoHandler, opts ...server.HandlerOption) error {
	type two interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Two struct {
		two
	}
	h := &twoHandler{hdlr}
	return s.Handle(s.NewHandler(&Two{h}, opts...))
}

type twoHandler struct {
	TwoHandler
}

func (h *twoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.TwoHandler.Call(ctx, in, out)
}

func (h *twoHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.TwoHandler.ClientStream(ctx, &twoClientStreamStream{stream})
}

type Two_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type twoClientStreamStream struct {
	stream server.Stream
}

func (x *twoClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *twoClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twoClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twoClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twoClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *twoHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TwoHandler.ServerStream(ctx, m, &twoServerStreamStream{stream})
}

type Two_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type twoServerStreamStream struct {
	stream server.Stream
}

func (x *twoServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *twoServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twoServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twoServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twoServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *twoHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.TwoHandler.BidiStream(ctx, &twoBidiStreamStream{stream})
}

type Two_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type twoBidiStreamStream struct {
	stream server.Stream
}

func (x *twoBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *twoBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twoBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twoBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twoBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *twoBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
